networks:
  shared_network:
    external: true
  laravel:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16

x-php-common: &php-common
  image: lukisa-php:latest
  build:
    context: ./docker/php
    dockerfile: Dockerfile
    args:
      - UID=${UID:-1000}
      - GID=${GID:-1000}
      - USER=${USER:-laravel}
  user: "${UID}:${GID}"
  volumes:
    - ./src:/var/www/html:z
    - .env:/var/www/html/.env
  working_dir: /var/www/html
  networks:
    - laravel
    - shared_network
  restart: always

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    restart: always
    container_name: nginx_lukisa
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www/html:z
      - .env:/var/www/html/.env
    depends_on:
      - php
      - reverb
      - redis
      - horizon
    networks:
      - laravel
      - shared_network

  php:
    <<: *php-common # Herda a configuração comum
    container_name: php_lukisa
    depends_on:
      - redis
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html:z
      - .env:/var/www/html/.env
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    devices:
      - /dev/dri:/dev/dri

  artisan:
    <<: *php-common
    container_name: artisan_lukisa
    profiles: ["artisan"]
    volumes:
      - ./src:/var/www/html:z
      - .env:/var/www/html/.env
    entrypoint: ['php', 'artisan']
    restart: "no"

  composer:
    <<: *php-common
    container_name: composer_lukisa
    profiles: ["composer"]
    volumes:
      - ./src:/var/www/html:z
      - .env:/var/www/html/.env
    entrypoint: ['composer']
    restart: "no"

  reverb:
    <<: *php-common
    container_name: reverb_lukisa
    ports:
      - "8080:8080"
    volumes:
      - ./src:/var/www/html:z
      - .env:/var/www/html/.env
    depends_on:
      - php
      - redis
    command: php artisan reverb:start --host=0.0.0.0 --port=8080

  horizon:
    <<: *php-common
    container_name: horizon_lukisa
    depends_on:
      - redis
    volumes:
      - ./src:/var/www/html:z
      - .env:/var/www/html/.env
    command: php artisan horizon
    devices:
      - /dev/dri:/dev/dri

  scheduler:
    <<: *php-common
    container_name: scheduler_lukisa
    depends_on:
      - redis
    volumes:
      - ./src:/var/www/html:z
      - .env:/var/www/html/.env
    command: php artisan schedule:work

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: node_lukisa
    user: "${UID}:${GID}"
    volumes:
      - ./src:/var/www/html:z
      - .env:/var/www/html/.env
    ports:
      - 3000:3000
      - 3001:3001
      - 5173:5173
    working_dir: /var/www/html
    profiles: ["node"]
    networks:
      - laravel
      - shared_network

  redis:
    image: redis:7.2-alpine
    container_name: redis_lukisa
    restart: unless-stopped
    ports:
      - "6378:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    sysctls:
      - net.core.somaxconn=1024
    volumes:
      - redis_data:/data
    networks:
      - laravel
      - shared_network

volumes:
  redis_data:
    driver: local