networks:
  shared_network:
    external: true
  laravel:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    restart: always
    container_name: nginx_lukisa
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/html/.env
    depends_on:
      - php
    networks:
      - laravel
      - shared_network

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: php_lukisa
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/html/.env
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    restart: always
    networks:
      - laravel
      - shared_network
    devices:
      - /dev/dri:/dev/dri 

  artisan:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: artisan_lukisa
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/html/.env
    working_dir: /var/www/html
    profiles: ["artisan"]
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
      - shared_network

  composer:
    build:
      context: ./docker/composer
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: composer_lukisa
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/html/.env
    working_dir: /var/www/html
    depends_on:
      - php
    user: ${USER:-laravel}
    profiles: ["composer"]
    entrypoint: ['composer', '--ignore-platform-reqs', '--no-scripts']
    networks:
      - laravel
      - shared_network

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: node_lukisa
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/html/.env
    ports:
      - 3000:3000
      - 3001:3001
      - 5173:5173
    working_dir: /var/www/html
    profiles: ["node"]
    networks:
      - laravel
      - shared_network